### ISSUE TITLE
Recording with USB or IP camera doesn't work

### ISSUE THREAD

**Issue by cedricve** [ChieftainY2k/rpi3-kerberosio-dockerized#13]
Because you've installed the .deb file, it will expect hardware encoding (which is ok as you're running on a RPI). However while trying to record kerberosio is throwing an encoding error:

    [h264_omx @ 0x342e2e0] OMX_GetHandle(OMX.broadcom.video_encode) failed: 80001005

Just wondering if something is missing (though you're running with privileged)

**Comment by ChieftainY2k** [comment]
Hello @cedricve 
I had this problem once but resolved it by running kerberos instance in privileged container.
