### ISSUE TITLE
Topic on forum.kerberos.io

### ISSUE THREAD

**Issue by cedricve** [ChieftainY2k/rpi3-kerberosio-dockerized#14]
Hey @ChieftainY2k 

FYI, we've created a topic on our new forum: https://forum.kerberos.io/t/kerberos-io-in-a-dockerized-raspberry-pi-3-environment-with-local-camera-stream-with-raspicam/21.

Cédric

**Comment by ChieftainY2k** [comment]
Hi! Cool!
I've updated the README and docs to better reflect what this project is
about (...sort of evolved into kind of a IoT sureveillance platform where
Kerberos.io is the core feature)
Tom.



--
"You pick a job you love, you never work in life."

**Comment by cedricve** [comment]
Hey Tom,

Yeah we love what you're doing, and are following up your work ;)

Amazing work 👍 

Cédric

**Comment by drphil3d** [comment]
Great work! I love what your doing, I installed on my raspberry pi last night and it works great, love all the features you have implemented.
https://youtu.be/m_suArkNHsU

**Comment by ChieftainY2k** [comment]
Hi!
Thank you guys, nice to hear that! :)
I've some ideas I'll try to implement shortly to see how reliable the
docker platform is as a base for the surveillance platform, stay tuned :)
Tom.

**Comment by ChieftainY2k** [comment]
Hey, seems that forum.kerberos.io is down ? :)
