### ISSUE TITLE
Tryout kerberos 2.8.0

### ISSUE THREAD

**Issue by cedricve** [ChieftainY2k/rpi3-kerberosio-dockerized#31]
Hello,

Were you be able to test 2.8.0 as well?

https://github.com/ChieftainY2k/raspberry-garda/blob/324583eb8c1d7d2f5759707d68e37a68c1fb8539/services/kerberos/Dockerfile.kerberos#L24-L25

**Comment by ChieftainY2k** [comment]
Hi Cedric,

Thanks for getting in touch :)

Unfortunately it does not work with the following setup:
[2020-04-11 18:50:36][garda] Hardware: Raspberry Pi 3 Model B Plus Rev 1.3
[2020-04-11 18:50:36][garda] Kernel: Linux camback 4.19.66-v7+ #1253 SMP
Thu Aug 15 11:49:46 BST 2019 armv7l GNU/Linux
[2020-04-11 18:50:36][garda] OS: PRETTY_NAME="Raspbian GNU/Linux 9
(stretch)"
[2020-04-11 18:50:36][garda] Raspberry version for kerberos: 3

I'm getting:
terminate called after throwing an instance of 'std::out_of_range'
  what():  map::at
Aborted (core dumped)

See the full log attached.

The dockerfile for that is here:
https://github.com/ChieftainY2k/raspberry-garda/blob/feature/kerberos-2.8.0/services/kerberos/Dockerfile

Cheers!
--
"You pick a job you love, you never work in life."

**Comment by cedricve** [comment]
Is the docker image somewhere published?

**Comment by ChieftainY2k** [comment]
Unfortunately not yet as the gada project is still in an early alpha stage.
I will try to build upload some image next week, time.

**Comment by cedricve** [comment]
Ok no problem, just want to help upgrading the version, as the error indicates the use of an old config. Would you be able to share the config files you are using; so i can reproduce.

**Comment by ChieftainY2k** [comment]
Hi, see the files attached, that is my current config for 2.6.x

Cheers!
--
"You pick a job you love, you never work in life."

**Comment by ChieftainY2k** [comment]
Hi! I've just performed full configuration overwrite with the newest 2.8.0 version and so far so good , it works!. 
However, when I use the older config from 2.6.x the machinery stops working (core dump).

**Comment by cedricve** [comment]
Yes that might make sense as 2.8.0 added new features, which are not included in 2.6.1.
