### ISSUE TITLE
Create scripts to init/start/stop the dockerized ecosystem

### ISSUE THREAD

**Issue by ChieftainY2k** [ChieftainY2k/rpi3-kerberosio-dockerized#5]
Create a script to make it easier for inexperienced users start init the app after a fresh raspbian install.
- check if camera module is enabled
- install docker 
- install docker-compose
- start the containers

**Comment by cedricve** [comment]
cool, you can also upload the docker image to docker hub. So you don't need to rebuild.

**Comment by ChieftainY2k** [comment]
Yes, I will soon, once I stop tinkering with the current work in progress.
